<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Magpie</RootNamespace>
    <AssemblyName>Magpie</AssemblyName>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="YoutubeExplode" />
    <PackageReference Include="FFmpeg.AutoGen" />
    <PackageReference Include="Bardie.Logos.Contracts" />
    <PackageReference Include="Bardie.Logos.Channel" />
    <PackageReference Include="Bardie.Logos.Hosting" />
    <PackageReference Include="Bardie.Module.Source" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="Bardie.Module.Source.Debug" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="module.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
